### ISSUE TITLE
Pilot Flightplan Data / Frequency not showing

### ISSUE THREAD

**Issue by nepetadosmil** [aidanstevens29/dataserver#3]

**Comment by aidanstevens29** [comment]
Flight Plan data fixed in https://github.com/aidanstevens29/dataserver/commit/7cf3800acc96923dbbb26de9b4e188b69fe36eff

Pilot frequency is only sent over FSD by vPilot for AFV testing purposes. As it is now implemented on all pilot clients across the network, it will not be implemented in the dataserver :)
